run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - exportloopref
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - goprintffuncname
    - misspell
    - nakedret
    - noctx
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - typecheck
    - unconvert
    - unparam
    - whitespace

linters-settings:
  govet:
    enable:
      - atomicalign
      - shadow

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  dupl:
    threshold: 100

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gocyclo
        - goconst
        - errcheck

    - path: internal/api/handlers/.*\.go
      linters:
        - dupl

  max-issues-per-linter: 0
  max-same-issues: 0